// <auto-generated />
namespace Cimri.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class iban_is_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iban_is_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201709071811230_iban_is_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
