// <auto-generated />
namespace Cimri.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class datetime2BugFixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetime2BugFixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201710061538569_datetime2BugFixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
