// <auto-generated />
namespace Cimri.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class stock_and_product_redesinged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stock_and_product_redesinged));
        
        string IMigrationMetadata.Id
        {
            get { return "201711091950498_stock_and_product_redesinged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
