// <auto-generated />
namespace Cimri.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class keyFix2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(keyFix2));
        
        string IMigrationMetadata.Id
        {
            get { return "201710112130476_keyFix2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
